#include "Std_Types.h"

#define BTC_RX_CENLOC_ON 						1
#define BTC_RX_CENLOC_OFF 						2
#define BTC_RX_EXTLIGHTS_REVERSELIGHT_ON		21
#define BTC_RX_EXTLIGHTS_REVERSELIGHT_OFF		22
#define BTC_RX_EXTLIGHTS_HIGBEAM_ON				3
#define BTC_RX_EXTLIGHTS_HIGBEAM_OFF 			4
#define BTC_RX_EXTLIGHTS_FLASHHIGHBEAM_ON 		5
#define BTC_RX_EXTLIGHTS_FLASHHIGHBEAM_OFF 		6
#define BTC_RX_EXTLIGHTS_TURNSIGNALLEFT_ON 		7
#define BTC_RX_EXTLIGHTS_TURNSIGNALLEFT_OFF 	8
#define BTC_RX_ESTLIGHTS_TURNSIGNALRIGHT_ON 	9
#define BTC_RX_ESTLIGHTS_TURNSIGNALRIGHT_OFF 	10
#define BTC_RX_EXTLIGHTS_HAZARDLIGHT_ON 		11
#define BTC_RX_EXTLIGHTS_HAZARDLIGHT_OFF 		12
#define BTC_RX_EXTLIGHTS_FOGLIGHTFRONT_ON 		13
#define BTC_RX_EXTLIGHTS_FOGLIGHTFRONT_OFF 		14
#define BTC_RX_EXTLIGHTS_FOGLIGHTREAR_ON 		15
#define BTC_RX_EXTLIGHTS_FOGLIGHTREAR_OFF 		16
#define BTC_RX_EXTLIGHTS_BRAKELIGHTON 			17
#define BTC_RX_EXTLIGHTS_BRAKELIGHTOFF 			18
#define BTC_RX_EXTLIGHTS_POSITIONZERO			100
#define BTC_RX_EXTLIGHTS_AUTOMATICLIGHTS		101
#define BTC_RX_EXTLIGHTS_POSITIONLIGHTS			102
#define BTC_RX_EXTLIGHTS_NIGHTTIMELIGHTS		103
#define BTC_RX_INTLIGHTS_INTERIORLIGHT_ON 		19
#define BTC_RX_INTLIGHTS_INTERIORLIGHT_OFF 		20

EXTERN uint8 BtcReceivedDataOnBluetooth;

EXTERN void BtcMainFunction();
EXTERN StdReturnType BtcInit();
EXTERN StdReturnType BtcRxVal();
EXTERN StdReturnType BtcEnableUart();
