#include "Std_Types.h"

#define BTC_RX_CENLOC_ON 						1
#define BTC_RX_CENLOC_OFF 						2
#define BTC_RX_EXTLIGHTS_HIGBEAM_ON				3
#define BTC_RX_EXTLIGHTS_HIGBEAM_OFF 			4
#define BTC_RX_EXTLIGHTS_FLASHHIGHBEAM_ON 		5
#define BTC_RX_EXTLIGHTS_FLASHHIGHBEAM_OFF 		6
#define BTC_RX_EXTLIGHTS_TURNSIGNALLEFT_ON 		7
#define BTC_RX_EXTLIGHTS_TURNSIGNALLEFT_OFF 	8
#define BTC_RX_ESTLIGHTS_TURNSIGNALRIGHT_ON 	9
#define BTC_RX_ESTLIGHTS_TURNSIGNALRIGHT_OFF 	10
#define BTC_RX_EXTLIGHTS_HAZARDLIGHT_ON 		11
#define BTC_RX_EXTLIGHTS_HAZARDLIGHT_OFF 		12
#define BTC_RX_EXTLIGHTS_FOGLIGHTFRONT_ON 		13
#define BTC_RX_EXTLIGHTS_FOGLIGHTFRONT_OFF 		14
#define BTC_RX_EXTLIGHTS_FOGLIGHTREAR_ON 		15
#define BTC_RX_EXTLIGHTS_FOGLIGHTREAR_OFF 		16
#define BTC_RX_EXTLIGHTS_BRAKELIGHTON 			17
#define BTC_RX_EXTLIGHTS_BRAKELIGHTOFF 			18
#define BTC_RX_EXTLIGHTS_POSITIONZERO			100
#define BTC_RX_EXTLIGHTS_AUTOMATICLIGHTS		101
#define BTC_RX_EXTLIGHTS_POSITIONLIGHTS			102
#define BTC_RX_EXTLIGHTS_NIGHTTIMELIGHTS		103
#define BTC_RX_INTLIGHTS_INTERIORLIGHT_ON 		19
#define BTC_RX_INTLIGHTS_INTERIORLIGHT_OFF 		20
#define BTC_RX_HVAC_NORMALMODE_ON				200
#define BTC_RX_HVAC_RECIRCULATIONMODE_ON		201
#define BTC_RX_HVAC_AUTOMATICMODE_ON			202
#define BTC_RX_HVAC_BACKWINDOWDEFROSTON			203
#define BTC_RX_HVAC_BACKWINDOWDEFROSTOFF		204
#define BTC_RX_HVAC_WINDSHIELDDEFROST_ON		205
#define BTC_RX_HVAC_WINDSHIELDDEFROST_OFF		206
#define BTC_RX_HVAC_AC_ON						207
#define BTC_RX_HVAC_AC_OFF						208
#define BTC_RX_HVAC_LEGVENT_ON					209
#define BTC_RX_HVAC_LEGVENT_OFF					210
#define BTC_RX_HVAC_MIDVENT_ON					211
#define BTC_RX_HVAC_MIDVENT_OFF					212
#define BTC_RX_HVAC_WINDSHIELDVENT_ON			213
#define BTC_RX_HVAC_WINDSHIELDVENT_OFF			214
#define BTC_RX_HVAC_TEMPERATUREVALUE_MIN		150
#define BTC_RX_HVAC_TEMPERATUREVALUE_MAX		166
#define BTC_RX_HVAC_FANVALUE_MIN				170
#define BTC_RX_HVAC_FANVALUE_MAX				177


EXTERN uint8 BtcReceivedDataOnBluetooth;

EXTERN void BtcMainFunction();
EXTERN StdReturnType BtcInit();
EXTERN StdReturnType BtcRxVal();
EXTERN StdReturnType BtcEnableUart();
